<%@ include file="header.jspf" %>
<div class="eyebrow">EJERCICIO 01 · SERVLET + EL</div><h1>Cálculo académico</h1><p class="lead-copy">Cada evaluación cuenta. Calcula tu promedio ponderado.</p>
<div class="row g-4"><div class="col-lg-7"><section class="card shadow-sm panel"><h2>Ingresa tus notas</h2><p class="muted">Escala de 0 a 20, con hasta dos decimales.</p><form method="post" action="${pageContext.request.contextPath}/promedio">
<label class="form-label" for="nota1">APF1 · Avance de Proyecto Final 1 <span class="weight">30 %</span></label><input class="form-control" type="number" id="nota1" name="nota1" min="0" max="20" step="0.01" required placeholder="Ej. 16" value="<c:out value='${param.nota1}'/>">
<label class="form-label" for="nota2">APF2 · Avance de Proyecto Final 2 <span class="weight">30 %</span></label><input class="form-control" type="number" id="nota2" name="nota2" min="0" max="20" step="0.01" required placeholder="Ej. 15" value="<c:out value='${param.nota2}'/>">
<label class="form-label" for="nota3">PROY · Proyecto Final <span class="weight">40 %</span></label><input class="form-control" type="number" id="nota3" name="nota3" min="0" max="20" step="0.01" required placeholder="Ej. 18" value="<c:out value='${param.nota3}'/>">
<button class="btn btn-primary w-100 mt-4" type="submit">Calcular promedio &rarr;</button></form></section></div>
<div class="col-lg-5"><section class="card shadow-sm result-panel"><div class="eyebrow">TU RESULTADO</div><c:choose><c:when test="${not empty promedio}"><div class="score">${promedio}<small>/ 20</small></div><c:choose><c:when test="${aprobado}"><span class="badge rounded-pill text-bg-success">Aprobado</span><p class="mt-3">Alcanzaste la nota mínima de aprobación.</p></c:when><c:otherwise><span class="badge rounded-pill text-bg-danger">Desaprobado</span><p class="mt-3">El promedio es menor que 13. Continúa reforzando tus aprendizajes.</p></c:otherwise></c:choose></c:when><c:otherwise><div class="score placeholder-score">—<small>/ 20</small></div><p>Completa las tres notas para ver tu resultado aquí.</p></c:otherwise></c:choose><hr><h3>¿Cómo se calcula?</h3><p class="formula">(APF1 × 0.30) + (APF2 × 0.30) + (PROY × 0.40)</p><small>Regla de ejemplo: aprobado desde 13.00. La condición se evalúa antes del redondeo; el resultado se muestra con dos decimales.</small></section></div></div>
<%@ include file="footer.jspf" %>
