const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const esc = s => s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const view = n => fs.readFileSync(path.join(root,'src/main/webapp/WEB-INF/views',n+'.jsp'),'utf8');
const catalogo = view('catalogo').match(/<c:forEach[\s\S]*?<\/c:forEach>/)[0];
const acceso = view('acceso').match(/<c:if test="\$\{evaluado\}">[\s\S]*?<\/c:choose>\s*<\/c:if>/)[0];
const slot = (n, text) => `<div class="evidence" id="evidence${n}"><strong>Evidencia ${n}: ${text}</strong><p>Espacio reservado para tu captura de pantalla.</p><input type="file" accept="image/*" aria-label="Insertar captura ${n}" onchange="insertImage(this)"></div>`;
const code = s => `<pre><code>${esc(s)}</code></pre>`;
const html = `<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ficha de trabajo · Semana 6, sesión 12</title><style>
*{box-sizing:border-box}body{font-family:Calibri,Arial,sans-serif;color:#20352f;background:#edf1ee;margin:0;line-height:1.55}.sheet{background:white;max-width:950px;margin:30px auto;padding:55px 65px}h1{font-size:27px;line-height:1.25;color:#174f42;margin-bottom:10px}h2{font-size:19px;color:#174f42;border-bottom:1px solid #c8d8cf;padding-bottom:9px;margin-top:30px}h3{font-size:17px;margin-top:25px}p{font-size:14px}dt{font-weight:bold;font-size:14px;margin-top:17px}dd{margin:7px 0 17px;font-size:14px}.meta{color:#58685f}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f1f5f2;padding:16px;font-size:11px;line-height:1.6;border-left:3px solid #548f73}code{font-family:Consolas,monospace}.evidence{border:2px dashed #c5d4cb;min-height:210px;margin:24px 0;padding:24px;text-align:center;background:#fafcfb;break-inside:avoid}.evidence p{color:#738279}.evidence img{display:block;max-width:100%;height:auto;margin:15px auto}.toolbar{max-width:950px;margin:20px auto;text-align:right}.toolbar button{padding:11px 18px;border:0;background:#175b49;color:white;border-radius:6px;cursor:pointer;margin-left:8px}table{border-collapse:collapse;width:100%;font-size:11px}th,td{border:1px solid #ced9d1;padding:10px;text-align:left;vertical-align:top}th{background:#edf4ef}label.check{display:block;margin:12px 0;font-size:14px}a{color:#175b49}.note{font-size:12px;color:#627369}.kicker{font-size:11px;letter-spacing:2px;color:#658173}.edit{outline-offset:5px}@media print{@page{size:A4;margin:16mm}body{background:white}.sheet{padding:0;margin:0;max-width:none}.toolbar,input[type=file]{display:none}h2,h3,dt{break-after:avoid}pre{font-size:9px}thead{display:table-header-group}.rubric{break-before:page}a{color:inherit;text-decoration:none}}
</style></head><body><div class="toolbar"><button onclick="saveCopy()">Guardar ficha con cambios</button><button onclick="window.print()">Imprimir / Guardar PDF</button></div><article class="sheet">
<div class="edit" contenteditable="true"><div class="kicker">DESARROLLO WEB INTEGRADO · UNIDAD 2</div><h1>Ficha de trabajo de laboratorio<br>Semana 6 · Sesión 12</h1><p class="meta"><strong>Docente:</strong> Mtro. Ing. César A. Cárdenas Latorre | Sede Arequipa<br><strong>Unidad:</strong> Aplicaciones Web y Patrones de Diseño</p>
<h2>I. Datos generales del estudiante</h2><p><strong>Apellidos y nombres:</strong> JORGE EDUARDO ACOSTA LOYOLA<br><strong>Código de estudiante:</strong> U22205593<br><strong>Carrera:</strong> Ingeniería de Sistemas e Informática<br><strong>Fecha:</strong> 17 / 09 / 2026</p>
<h2>II. Desarrollo de los ejercicios prácticos</h2><p>Aplicación MVC ejecutada en Tomcat, con Bootstrap local, Servlet controlador y vistas JSP con JSTL y Expression Language. Las vistas se encuentran en WEB-INF y no contienen scriptlets. El descriptor web.xml prohíbe su uso mediante scripting-invalid.</p>
<h3>Ejercicio 1: Cálculo Académico con Servlet y EL</h3><dl><dt>Breve descripción de la lógica implementada en el Servlet:</dt><dd>El Servlet recibe tres notas por POST, valida que sean números entre 0 y 20 con hasta dos decimales y calcula el promedio ponderado con BigDecimal. Para este ejercicio se adoptan los pesos de APF1: Avance de Proyecto Final 1 (30 %), APF2: Avance de Proyecto Final 2 (30 %) y PROY: Proyecto Final (40 %), ya que la ficha no define ponderaciones. La aprobación se fija en 13. El resultado se redondea a dos decimales para mostrarlo; la condición de aprobación utiliza el valor sin redondear. El controlador publica promedio y aprobado mediante setAttribute y realiza forward al JSP. Las entradas inválidas muestran un mensaje y una respuesta HTTP 400.</dd></dl>
${code('BigDecimal promedio = n1.multiply(new BigDecimal("0.30"))\n    .add(n2.multiply(new BigDecimal("0.30")))\n    .add(n3.multiply(new BigDecimal("0.40")));\nreq.setAttribute("promedio", promedio.setScale(2, RoundingMode.HALF_UP));\nreq.setAttribute("aprobado", promedio.compareTo(new BigDecimal("13")) >= 0);')}
<dl><dt>Fragmento de código Expression Language (EL) utilizado en el JSP para mostrar el promedio ponderado:</dt></dl>${code('<div class="score">${promedio}<small>/ 20</small></div>')}<p><strong>Ejemplo para la evidencia:</strong> 16, 15 y 18 producen un promedio de 16.50 y estado Aprobado.</p></div>
${slot(1,'formulario de cálculo y resultado con Bootstrap')}
<div class="edit" contenteditable="true"><h3>Ejercicio 2: Catálogo Dinámico con JSTL Core (&lt;c:forEach&gt;)</h3><dl><dt>¿Qué atributo de la etiqueta &lt;c:forEach&gt; utilizó para enlazar la lista proveniente del Servlet?</dt><dd>Utilicé el atributo <code>items="\$\{productos\}"</code>. La expresión EL recupera la lista publicada con <code>req.setAttribute("productos", PRODUCTOS)</code>. El atributo <code>var="producto"</code> representa el elemento actual. Sus propiedades se resuelven mediante los getters de la clase Producto.</dd><dt>Fragmento de código de la tabla dinámica con JSTL:</dt></dl>${code(catalogo)}<p>El bloque se encuentra dentro de tbody. La biblioteca Core se declara con <code>&lt;%@ taglib prefix="c" uri="jakarta.tags.core" %&gt;</code>. Se usa fmt:formatNumber para presentar los precios y c:choose para indicar disponibilidad. Los seis productos son datos de demostración definidos en el controlador.</p></div>
${slot(2,'tabla renderizada con seis productos')}
<div class="edit" contenteditable="true"><h3>Ejercicio 3: Validación Condicional de Acceso (&lt;c:if&gt; / &lt;c:choose&gt;)</h3><dl><dt>¿Cómo evaluó la condición de acceso utilizando JSTL y EL en la vista?</dt><dd>El Servlet valida el nombre y la edad entera entre 0 y 120; luego publica nombre, edad, matriculaActiva y evaluado en el request. En la vista, c:if comprueba si ya hubo una evaluación. Dentro de c:choose, c:when utiliza <code>\$\{edad ge 18 and matriculaActiva\}</code>: el ingreso se permite cuando ambas condiciones son verdaderas. c:otherwise muestra el rechazo, y dos etiquetas c:if explican las condiciones incumplidas. c:out escapa el nombre recibido del usuario. La regla es didáctica, pues la ficha no establece un criterio de acceso; no implementa autenticación real.</dd></dl>${code(acceso)}<p><strong>Ejemplos:</strong> edad 22 y matrícula activa → Acceso permitido. Edad 17 y matrícula inactiva → Acceso denegado con ambos motivos.</p></div>
${slot(3,'mensaje condicional dinámico de acceso')}
<div class="edit" contenteditable="true"><h2>III. Autoevaluación del estudiante</h2><p>Indique con un check (✔) su nivel de logro frente a los objetivos de la sesión:</p></div>
<label class="check"><input type="checkbox" onchange="this.toggleAttribute('checked',this.checked)"> Comprendo la importancia de eliminar scriptlets de Java y aplicar JSTL + EL.</label><label class="check"><input type="checkbox" onchange="this.toggleAttribute('checked',this.checked)"> Sé configurar y utilizar la librería Core de JSTL (&lt;c:forEach&gt;, &lt;c:if&gt;) en un JSP.</label><label class="check"><input type="checkbox" onchange="this.toggleAttribute('checked',this.checked)"> Logré integrar el Servlet controlador con la vista mediante atributos del request.</label>
<p class="note">La autoevaluación debe ser completada personalmente por el estudiante.</p>
<div class="edit rubric" contenteditable="true"><h2>Rúbrica de evaluación de laboratorio</h2><p>Escala vigesimal: 0–20. Cuatro criterios de hasta 5 puntos cada uno.</p><table><thead><tr><th>Criterios de evaluación</th><th>Logrado (4–5 puntos)</th><th>En proceso (2–3 puntos)</th><th>En inicio (0–1 punto)</th></tr></thead><tbody>
<tr><td><strong>1. Separación de capas y uso de JSTL / EL</strong></td><td>Aplica estrictamente el estándar exigido: cero scriptlets (&lt;% %&gt;) en la vista, utilizando correctamente Expression Language y etiquetas JSTL.</td><td>Utiliza JSTL y EL parcialmente, pero mantiene algún scriptlet o llamada directa a métodos Java en la vista.</td><td>No utiliza JSTL ni EL; todo el desarrollo se basa en Java incrustado.</td></tr>
<tr><td><strong>2. Funcionamiento y lógica (MVC)</strong></td><td>El Servlet procesa adecuadamente los datos, gestiona atributos con setAttribute y la vista los renderiza sin errores.</td><td>El sistema funciona parcialmente; presenta errores menores al pasar atributos o interpretar datos.</td><td>No compila, presenta errores críticos en Tomcat o no cumple el flujo MVC.</td></tr>
<tr><td><strong>3. Implementación de etiquetas Core</strong></td><td>Implementa con precisión iteraciones y validaciones condicionales dinámicas conectadas al modelo.</td><td>Implementa etiquetas con errores de sintaxis en atributos como items o test.</td><td>No logra implementar las etiquetas JSTL Core solicitadas.</td></tr>
<tr><td><strong>4. Presentación, estilo y ficha de trabajo</strong></td><td>Ficha completamente desarrollada, fragmentos de código limpios, Bootstrap y evidencias claras.</td><td>Ficha incompleta, capturas poco legibles o código desordenado.</td><td>No presenta la ficha ni las evidencias.</td></tr></tbody></table>
<h2>Guía para las capturas</h2><p>Abra <a href="http://localhost:8081/TallerS6s12/">http://localhost:8081/TallerS6s12/</a>, ejecute cada ejercicio y capture el formulario con su resultado. Inserte las imágenes en los tres espacios de esta ficha. Puede editar el texto directamente, marcar la autoevaluación y pulsar “Guardar ficha con cambios” para descargar una copia HTML con las imágenes incorporadas. “Imprimir / Guardar PDF” permite generar el documento final.</p><p class="note">Referencias técnicas: <a href="https://tomcat.apache.org/migration-10.1.html">Apache Tomcat 10.1</a> y <a href="https://jakarta.ee/specifications/tags/3.0/jakarta-tags-spec-3.0.pdf">Jakarta Tags 3.0</a>.</p></div></article>
<script>
function insertImage(input){const file=input.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const box=input.parentElement;let image=box.querySelector('img');if(!image){image=document.createElement('img');image.alt=box.querySelector('strong').textContent;box.insertBefore(image,input);}image.src=reader.result;box.querySelector('p').textContent='Captura incorporada. Puede reemplazarla seleccionando otra imagen.';};reader.readAsDataURL(file);}
function saveCopy(){const blob=new Blob(['<!DOCTYPE html>\\n'+document.documentElement.outerHTML],{type:'text/html;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='Ficha_S6_S12_Jorge_Acosta.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
</script></body></html>`;
fs.mkdirSync(path.join(root,'entregables'),{recursive:true});
fs.writeFileSync(path.join(root,'entregables/Ficha_S6_S12.html'),html);
console.log('Ficha HTML generada.');
